/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_araqne_winapi_EventLogApi */

#ifndef _Included_org_araqne_winapi_EventLogApi
#define _Included_org_araqne_winapi_EventLogApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_araqne_winapi_EventLogApi
 * Method:    subscribe
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_araqne_winapi_EventLogApi_subscribe
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_araqne_winapi_EventLogApi
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_araqne_winapi_EventLogApi_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_araqne_winapi_EventLogApi
 * Method:    read
 * Signature: (JI)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_araqne_winapi_EventLogApi_read
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_araqne_winapi_EventLogApi
 * Method:    getChannelPaths
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_araqne_winapi_EventLogApi_getChannelPaths
  (JNIEnv *, jclass);

/*
 * Class:     org_araqne_winapi_EventLogApi
 * Method:    lookupAccountSid
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_araqne_winapi_EventLogApi_lookupAccountSid
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
